### ISSUE TITLE
remove try-except block with reraise in config.parse.from_toml

### ISSUE THREAD

**Issue by NickleDave** [NickleDave/vak#204]
this one
```
    try:
        with toml_path.open('r') as fp:
            config_toml = toml.load(fp)
    except TomlDecodeError as e:
        raise Exception(f'Error when parsing .toml config file: {toml_path}') from e
```
that starts here:
https://github.com/NickleDave/vak/blob/071a85cef67396cd3a3565d6fb98713d3a51fdc8/src/vak/config/parse.py#L86

because it just obscures the actual important traceback and turns out to be not helpful, like in this error:
```
Traceback (most recent call last):
  File "/home/art/Documents/repos/coding/birdsong/vak/src/vak/config/parse.py", line 88, in from_toml
    config_toml = toml.load(fp)
  File "/home/art/anaconda3/envs/vak-dev/lib/python3.6/site-packages/toml/decoder.py", line 134, in load
    return loads(f.read(), _dict, decoder)
  File "/home/art/anaconda3/envs/vak-dev/lib/python3.6/site-packages/toml/decoder.py", line 227, in loads
    original, i)
toml.decoder.TomlDecodeError: Found invalid character in key name: ':'. Try quoting the key name. (line 23 column 16 char 738)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/art/anaconda3/envs/vak-dev/bin/vak", line 11, in <module>
    load_entry_point('vak', 'console_scripts', 'vak')()
  File "/home/art/Documents/repos/coding/birdsong/vak/src/vak/__main__.py", line 44, in main
    config_file=args.configfile)
  File "/home/art/Documents/repos/coding/birdsong/vak/src/vak/cli/cli.py", line 19, in cli
    prep(toml_path=config_file)
  File "/home/art/Documents/repos/coding/birdsong/vak/src/vak/cli/prep.py", line 46, in prep
    cfg = config.parse.from_toml(toml_path, sections=['PREP', 'SPECTROGRAM', 'DATALOADER'])
  File "/home/art/Documents/repos/coding/birdsong/vak/src/vak/config/parse.py", line 90, in from_toml
    raise Exception(f'Error when parsing .toml config file: {toml_path}') from e
Exception: Error when parsing .toml config file: gy6or6_predict.toml
```

**Comment by NickleDave** [comment]
Actually after looking at it some more, I think this is still more informative, since it explains that the error is from the config file and specifies the file
