### ISSUE TITLE
transitions between calculations of validation measures and model training take a long time

### ISSUE THREAD

**Issue by yardencsGitHub** [NickleDave/vak#208]
The process of continuous training steps or the evaluation of the validation set progresses fast and nicely.
But, between these alternating phases there are lengthy pauses ..

**Comment by NickleDave** [comment]
Need to test if this is still the case.  
Not clear to me if this was Windows related

**Comment by NickleDave** [comment]
Tested on Pop!OS (i.e., ubuntu) using the llb3 data and I did not have this issue. Need to test on Windows next

**Comment by NickleDave** [comment]
Tried to test this on Windows in a conda env but I am getting weird cryptic low-level errors when I try to run `vak prep`:  
```
(tweety-env) C:\Users\Nickl\Documents\repos\python\tweetynet\article>vak prep data\configs\Canaries\llb3\llb3-test-eval-switch-speed.toml
2022-08-14 15:09:58,988 - vak.cli.prep - INFO - Determined that purpose of config file is: train.
Will add 'csv_path' option to 'TRAIN' section.
2022-08-14 15:09:58,989 - vak.core.prep - INFO - purpose for dataset: train
2022-08-14 15:09:58,989 - vak.core.prep - INFO - will split dataset
2022-08-14 15:10:04,822 - vak.io.dataframe - INFO - creating dataset from spectrogram files in: C:\Users\Nickl\Documents\Data\vocal\tweetynet-canary\llb3\annotated
2022-08-14 15:10:04,979 - vak.files.spect - INFO - validating set of spectrogram files
[                                        ] | 0% Completed | 7.01 sTraceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Nickl\miniconda3\envs\tweety-env\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\Nickl\miniconda3\envs\tweety-env\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\Nickl\miniconda3\envs\tweety-env\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\Nickl\miniconda3\envs\tweety-env\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\Nickl\miniconda3\envs\tweety-env\lib\runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\Nickl\miniconda3\envs\tweety-env\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\Nickl\miniconda3\envs\tweety-env\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Nickl\miniconda3\envs\tweety-env\Scripts\vak-script.py", line 5, in <module>
    from vak.__main__ import main
  File "C:\Users\Nickl\miniconda3\envs\tweety-env\lib\site-packages\vak\__init__.py", line 13, in <module>
    from . import (
  File "C:\Users\Nickl\miniconda3\envs\tweety-env\lib\site-packages\vak\cli\__init__.py", line 4, in <module>
    from . import cli, eval, learncurve, predict, prep, train
  File "C:\Users\Nickl\miniconda3\envs\tweety-env\lib\site-packages\vak\cli\cli.py", line 1, in <module>
    from .eval import eval
  File "C:\Users\Nickl\miniconda3\envs\tweety-env\lib\site-packages\vak\cli\eval.py", line 4, in <module>
    from .. import (
  File "C:\Users\Nickl\miniconda3\envs\tweety-env\lib\site-packages\vak\config\__init__.py", line 2, in <module>
    from . import (
  File "C:\Users\Nickl\miniconda3\envs\tweety-env\lib\site-packages\vak\config\config.py", line 5, in <module>
    from .eval import EvalConfig
  File "C:\Users\Nickl\miniconda3\envs\tweety-env\lib\site-packages\vak\config\eval.py", line 6, in <module>
    from .validators import is_a_directory, is_a_file, is_valid_model_name
  File "C:\Users\Nickl\miniconda3\envs\tweety-env\lib\site-packages\vak\config\validators.py", line 7, in <module>
    from .. import models
  File "C:\Users\Nickl\miniconda3\envs\tweety-env\lib\site-packages\vak\models\__init__.py", line 2, in <module>
    from . import teenytweetynet
  File "C:\Users\Nickl\miniconda3\envs\tweety-env\lib\site-packages\vak\models\teenytweetynet.py", line 1, in <module>
    import torch
  File "C:\Users\Nickl\miniconda3\envs\tweety-env\lib\site-packages\torch\__init__.py", line 129, in <module>
    raise err
OSError: [WinError 1455] The paging file is too small for this operation to complete. Error loading "C:\Users\Nickl\miniconda3\envs\tweety-env\lib\site-packages\torch\lib\shm.dll" or one of its dependencies.
```
After this error the command prompt freezes or else crashes. So, that's good.  

I created the environment with the following commands:
```
conda create -n tweety-env python=3.9
conda activate tweety-env
conda install pytorch torchvision cudatoolkit=11.6 -c pytorch -c conda-forge
conda install vak tweetynet -c conda-forge
```

My guess is the very new version of cudatoolkit off conda-forge and/or the fact that vak + tweetynet were not compiled with these new versions are giving rise to the low-level error?
