### ISSUE TITLE
vak.split.algorithms.brute_force fails sometimes on llb3 test dataset, gives incorrect error message

### ISSUE THREAD

**Issue by NickleDave** [NickleDave/vak#259]
I'm fixing the tests, using a setup .toml config that runs on the "mini" canary dataset from llb3

Problem is, It fails more often than not when splitting the dataset into `train` and `val` sets.

The error is:
```
Total target duration of splits: 468.0 seconds. Will be drawn from dataset with total duration: 479.876.
Traceback (most recent call last):
  File "./tests/setup_scripts/rerun_prep.py", line 30, in <module>
    main()
  File "./tests/setup_scripts/rerun_prep.py", line 26, in main
    vak.cli.prep(toml_path=test_toml_path)
  File "/Users/davidnicholson/Documents/repos/coding/vocal/vak/src/vak/cli/prep.py", line 108, in prep
    logger=logger,
  File "/Users/davidnicholson/Documents/repos/coding/vocal/vak/src/vak/core/prep.py", line 220, in prep
    logger=logger)
  File "/Users/davidnicholson/Documents/repos/coding/vocal/vak/src/vak/split/split.py", line 149, in dataframe
    logger=logger)
  File "/Users/davidnicholson/Documents/repos/coding/vocal/vak/src/vak/split/split.py", line 87, in train_test_dur_split_inds
    test_dur)
  File "/Users/davidnicholson/Documents/repos/coding/vocal/vak/src/vak/split/algorithms/bruteforce.py", line 109, in brute_force
    f'unable to split dataset so that each split has an instance of label: {label}.'
ValueError: unable to split dataset so that each split has an instance of label: 19.There were only 0 files with that label, but there are 2 splits
```

Sometimes it says there is 1 file with that label. However there are definitely not 0 files with that label.
Here's how I get the label counts.
```
from collections import Counter

import gardner  # package from tweetynet repo with 'yarden2annot' that parses annotation
import crowsetta

scribe = crowsetta.Transcriber(annot_format='yarden')
annots = scribe.from_file('llb3_annot_subset.mat')

labelcounts = Counter()

for annot in annots:
     labelcounts.update(annot.seq.labels)

print(labelcounts)
Counter({'6': 176,
         '3': 3176,
         '8': 356,
         '10': 46,
         '16': 4,
         '18': 308,
         '1': 636,
         '2': 395,
         '14': 137,
         '11': 285,
         '9': 101,
         '7': 84,
         '13': 73,
         '12': 80,
         '17': 38,
         '19': 84})
```
note there are 84 occurrences of label 19.

so it looks to me like `vak.split.algorithms.brute_force` is running out of files to add, and then incorrectly reporting the number of files left -- it has zero files **left** with label 19 in them

**Comment by NickleDave** [comment]
Pretty sure this was fixed by the rewrite in #300 

`brute_force` is now passing unit tests as of #309
