### ISSUE TITLE
`train_dur_csv_paths.from_dir` does not use just `train` split to compute spect vectors

### ISSUE THREAD

**Issue by yardencsGitHub** [NickleDave/vak#328]
Traceback (most recent call last):
  File "/home/yardenc/anaconda3/envs/vak_env/bin/vak", line 8, in <module>
    sys.exit(main())
  File "/home/yardenc/anaconda3/envs/vak_env/lib/python3.8/site-packages/vak/__main__.py", line 43, in main
    cli(command=args.command,
  File "/home/yardenc/anaconda3/envs/vak_env/lib/python3.8/site-packages/vak/cli/cli.py", line 31, in cli
    learning_curve(toml_path=config_file)
  File "/home/yardenc/anaconda3/envs/vak_env/lib/python3.8/site-packages/vak/cli/learncurve.py", line 51, in learning_curve
    core.learning_curve(model_config_map,
  File "/home/yardenc/anaconda3/envs/vak_env/lib/python3.8/site-packages/vak/core/learncurve/learncurve.py", line 188, in learning_curve
    train_dur_csv_paths = _train_dur_csv_paths.from_dir(previous_run_path,
  File "/home/yardenc/anaconda3/envs/vak_env/lib/python3.8/site-packages/vak/core/learncurve/train_dur_csv_paths.py", line 149, in from_dir
    x_inds) = WindowDataset.spect_vectors_from_df(subset_df,
  File "/home/yardenc/anaconda3/envs/vak_env/lib/python3.8/site-packages/vak/datasets/window_dataset.py", line 584, in spect_vectors_from_df
    x_inds) = WindowDataset.crop_spect_vectors_keep_classes(lbl_tb,
  File "/home/yardenc/anaconda3/envs/vak_env/lib/python3.8/site-packages/vak/datasets/window_dataset.py", line 435, in crop_spect_vectors_keep_classes
    raise ValueError(
ValueError: was not able to crop spect vectors to specified duration in a way that maintained all classes in dataset

**Comment by yardencsGitHub** [comment]
@NickleDave , 
I managed to set VS code to debug the site-package vak.
Several observations can contribute to the error:
-- When running with the previous_run_path  I get to line 145 in core/learncurve/train_dur_csv_paths.py
(in the function 'from_dir')
The dataframe created in this line (subset_df = pd.read_csv(csv_path)) has multiple 'index' columns that were not dropped in whatever pandas operations .. this is probably not the issue :)

But, unlike the code for running new experiments (the function 'from_df'), the dataframe is not cropped to have only files marked as the  'train' split.

I am going to add that line (subset_df = subset_df[subset_df['split'] == 'train'] ) and see if this solves the issue.

**Comment by yardencsGitHub** [comment]
It works

**Comment by NickleDave** [comment]
:raised_hands: great! thank you

Let me stare at it and see if this makes sense to me.

if so I'll fix right away

and yes

> The dataframe created in this line (subset_df = pd.read_csv(csv_path)) has multiple 'index' columns that were not dropped in whatever pandas operations .. this is probably not the issue :)

this probably needs a `to_csv(index=False)` somewhere although I thought had fixed that. Will double check

**Comment by NickleDave** [comment]
yes this definitely looks like a copy-paste error on my part, fixing now.

thank you for catching it, I had it on the to-do list today but was dreading the thought of trying to figure out how I messed up the cropping. 
This looks like a much simpler thing to fix

**Comment by NickleDave** [comment]
- [ ] be sure to use just `train` split from loaded `DataFrame` in `from_dirs`
- [ ] use clearer naming, e.g. `train_subset_df`
