### ISSUE TITLE
Vak crashes when .cbin files dont have corresponding .rec files

### ISSUE THREAD

**Issue by NickleDave** [NickleDave/vak#411]
from @avanikop -- copying this issue from the `tweetynet` repo:

Hi!
One minor issue I was facing while using the vak prep predict.toml step:
When my data folder is missing some .rec files (but the corresponding .cbin files are present), vak crashes as the prep predict step. Traceback is as follows:

`Traceback (most recent call last):
  File "c:\users\avani\anaconda3\dir\envs\vak-env\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\avani\anaconda3\dir\envs\vak-env\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\avani\anaconda3\dir\envs\vak-env\Scripts\vak.exe\__main__.py", line 7, in <module>
  File "c:\users\avani\anaconda3\dir\envs\vak-env\lib\site-packages\vak\__main__.py", line 44, in main
    config_file=args.configfile)
  File "c:\users\avani\anaconda3\dir\envs\vak-env\lib\site-packages\vak\cli\cli.py", line 19, in cli
    prep(toml_path=config_file)
  File "c:\users\avani\anaconda3\dir\envs\vak-env\lib\site-packages\vak\cli\prep.py", line 108, in prep
    logger=logger,
  File "c:\users\avani\anaconda3\dir\envs\vak-env\lib\site-packages\vak\core\prep.py", line 210, in prep
    logger=logger)
  File "c:\users\avani\anaconda3\dir\envs\vak-env\lib\site-packages\vak\io\dataframe.py", line 167, in from_files
    labelset=labelset)
  File "c:\users\avani\anaconda3\dir\envs\vak-env\lib\site-packages\vak\io\audio.py", line 213, in to_spect
    spect_files = list(bag.map(_spect_file))
  File "c:\users\avani\anaconda3\dir\envs\vak-env\lib\site-packages\dask\bag\core.py", line 1426, in __iter__
    return iter(self.compute())
  File "c:\users\avani\anaconda3\dir\envs\vak-env\lib\site-packages\dask\base.py", line 279, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "c:\users\avani\anaconda3\dir\envs\vak-env\lib\site-packages\dask\base.py", line 567, in compute
    results = schedule(dsk, keys, **kwargs)
  File "c:\users\avani\anaconda3\dir\envs\vak-env\lib\site-packages\dask\multiprocessing.py", line 228, in get
    **kwargs
  File "c:\users\avani\anaconda3\dir\envs\vak-env\lib\site-packages\dask\local.py", line 486, in get_async
    raise_exception(exc, tb)
  File "c:\users\avani\anaconda3\dir\envs\vak-env\lib\site-packages\dask\multiprocessing.py", line 119, in reraise
    raise exc
dask.multiprocessing.FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\avani\\OneDrive\\Documents\\Veit_lab_data\\analysis\\pk92r45_MMAN\\20110524_solo\\010611\\pk92r45_010611_135237.10591.rec'

Traceback
---------
  File "c:\users\avani\anaconda3\dir\envs\vak-env\lib\site-packages\dask\local.py", line 222, in execute_task
    result = _execute_task(task, data)
  File "c:\users\avani\anaconda3\dir\envs\vak-env\lib\site-packages\dask\core.py", line 121, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "c:\users\avani\anaconda3\dir\envs\vak-env\lib\site-packages\dask\bag\core.py", line 1791, in reify
    seq = list(seq)
  File "c:\users\avani\anaconda3\dir\envs\vak-env\lib\site-packages\dask\bag\core.py", line 1978, in __next__
    return self.f(*vals)
  File "c:\users\avani\anaconda3\dir\envs\vak-env\lib\site-packages\vak\io\audio.py", line 194, in _spect_file
    fs, dat = constants.AUDIO_FORMAT_FUNC_MAP[audio_format](audio_file)
  File "c:\users\avani\anaconda3\dir\envs\vak-env\lib\site-packages\vak\constants.py", line 14, in new_f
    return_tuple = func(*args, **kwargs)
  File "c:\users\avani\anaconda3\dir\envs\vak-env\lib\site-packages\evfuncs\evfuncs.py", line 172, in load_cbin
    rec_dict = readrecf(recfile)
  File "c:\users\avani\anaconda3\dir\envs\vak-env\lib\site-packages\evfuncs\evfuncs.py", line 60, in readrecf
    with open(filename, 'r') as recfile:`

I tried solving this issue by creating a 'fake' rec file ie I copy details from an existing rec file and rename it appropriately. I made sure that Fs (sampling frequency) info was present in the rec file because that is what vak reads from the rec file. Unfortunately, I ran into another error:

`
Traceback (most recent call last): File 
"C:\Users\avani\anaconda3\dir\envs\vak040b6\lib\runpy.py", line 194, 
in _run_module_as_main return _run_code(code, main_globals, None, File 
"C:\Users\avani\anaconda3\dir\envs\vak040b6\lib\runpy.py", line 87, in 
_run_code exec(code, run_globals) File 
"C:\Users\avani\anaconda3\dir\envs\vak040b6\Scripts\vak.exe\__main__.py", line 
7, in <module> File 
"C:\Users\avani\anaconda3\dir\envs\vak040b6\lib\site-packages\vak\__main__.py", line 45, in main cli.cli(command=args.command, config_file=args.configfile) File "C:\Users\avani\anaconda3\dir\envs\vak040b6\lib\site-packages\vak\cli\cli.py", line 30, in cli COMMAND_FUNCTION_MAP[command](toml_path=config_file) File "C:\Users\avani\anaconda3\dir\envs\vak040b6\lib\site-packages\vak\cli\prep.py", line 132, in prep vak_df, csv_path = core.prep( File "C:\Users\avani\anaconda3\dir\envs\vak040b6\lib\site-packages\vak\core\prep.py", line 205, in prep vak_df = dataframe.from_files( File "C:\Users\avani\anaconda3\dir\envs\vak040b6\lib\site-packages\vak\io\dataframe.py", line 133, in from_files spect_files = audio.to_spect( File "C:\Users\avani\anaconda3\dir\envs\vak040b6\lib\site-packages\vak\io\audio.py", line 234, in to_spect spect_files = list(bag.map(_spect_file)) File "C:\Users\avani\anaconda3\dir\envs\vak040b6\lib\site-packages\dask\bag\core.py", line 1467, in __iter__ return iter(self.compute()) File "C:\Users\avani\anaconda3\dir\envs\vak040b6\lib\site-packages\dask\base.py", line 288, in compute (result,) = compute(self, traverse=False, **kwargs) File "C:\Users\avani\anaconda3\dir\envs\vak040b6\lib\site-packages\dask\base.py", line 571, in compute results = schedule(dsk, keys, **kwargs) File "C:\Users\avani\anaconda3\dir\envs\vak040b6\lib\site-packages\dask\multiprocessing.py", line 219, in get result = get_async( File "C:\Users\avani\anaconda3\dir\envs\vak040b6\lib\site-packages\dask\local.py", line 507, in get_async raise_exception(exc, tb) File "C:\Users\avani\anaconda3\dir\envs\vak040b6\lib\site-packages\dask\multiprocessing.py", line 109, in reraise raise exc dask.multiprocessing.KeyError: 'num_channels' Traceback --------- File "C:\Users\avani\anaconda3\dir\envs\vak040b6\lib\site-packages\dask\local.py", line 220, in execute_task result = _execute_task(task, data) File "C:\Users\avani\anaconda3\dir\envs\vak040b6\lib\site-packages\dask\core.py", line 119, in _execute_task return func(*(_execute_task(a, cache) for a in args)) File "C:\Users\avani\anaconda3\dir\envs\vak040b6\lib\site-packages\dask\bag\core.py", line 1833, in reify seq = list(seq) File "C:\Users\avani\anaconda3\dir\envs\vak040b6\lib\site-packages\dask\bag\core.py", line 2021, in __next__ return self.f(*vals) File "C:\Users\avani\anaconda3\dir\envs\vak040b6\lib\site-packages\vak\io\audio.py", line 211, in _spect_file dat, fs = constants.AUDIO_FORMAT_FUNC_MAP[audio_format](audio_file) File "C:\Users\avani\anaconda3\dir\envs\vak040b6\lib\site-packages\evfuncs\evfuncs.py", line 179, in load_cbin data = data[channel::rec_dict['num_channels']] # step by number of 
channels`

Not a very urgent issue, and probably specific to my case!

**Comment by NickleDave** [comment]
Closing this for now but it's in history in case someone searches
