### ISSUE TITLE
DOC/BUG: config class docstrings are not appearing in reference section of docs

### ISSUE THREAD

**Issue by NickleDave** [NickleDave/vak#457]
Must have happened after switching to `furo`?

**Comment by NickleDave** [comment]
Looks like this is happening on readthedocs because `sndilfe` library is not found

```
WARNING: autodoc: failed to import class 'config.config.Config' from module 'vak'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/vak/envs/latest/lib/python3.8/site-packages/sphinx/ext/autodoc/importer.py", line 70, in import_module
    return importlib.import_module(modname)
  File "/home/docs/.asdf/installs/python/3.8.12/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/docs/checkouts/readthedocs.org/user_builds/vak/envs/latest/lib/python3.8/site-packages/vak/__init__.py", line 13, in <module>
    from . import (
  File "/home/docs/checkouts/readthedocs.org/user_builds/vak/envs/latest/lib/python3.8/site-packages/vak/annotation.py", line 6, in <module>
    import crowsetta
  File "/home/docs/checkouts/readthedocs.org/user_builds/vak/envs/latest/lib/python3.8/site-packages/crowsetta/__init__.py", line 13, in <module>
    from .transcriber import Transcriber
  File "/home/docs/checkouts/readthedocs.org/user_builds/vak/envs/latest/lib/python3.8/site-packages/crowsetta/transcriber.py", line 6, in <module>
    from . import formats
  File "/home/docs/checkouts/readthedocs.org/user_builds/vak/envs/latest/lib/python3.8/site-packages/crowsetta/formats.py", line 8, in <module>
    setattr(current_module, entry_point.name, entry_point.load())
  File "/home/docs/checkouts/readthedocs.org/user_builds/vak/envs/latest/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2458, in load
    return self.resolve()
  File "/home/docs/checkouts/readthedocs.org/user_builds/vak/envs/latest/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2464, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/docs/checkouts/readthedocs.org/user_builds/vak/envs/latest/lib/python3.8/site-packages/crowsetta/birdsongrec.py", line 14, in <module>
    import soundfile
  File "/home/docs/checkouts/readthedocs.org/user_builds/vak/envs/latest/lib/python3.8/site-packages/soundfile.py", line 142, in <module>
    raise OSError('sndfile library not found')
OSError: sndfile library not found
```

I think the fix is to install `libsndfile` with `apt` in `.readthedocs.yml`

**Comment by NickleDave** [comment]
> I think the fix is to install libsndfile with apt in .readthedocs.yml

as shown here:
https://github.com/readthedocs/test-builds/blob/use-apt/.readthedocs.yaml
