### ISSUE TITLE
BUG: Error when eval directory contains only one file

### ISSUE THREAD

**Issue by vivinastase** [NickleDave/vak#467]
#### Before submitting a bug, please make sure the issue hasn't been already addressed by searching through [the past issues](https://github.com/NickleDave/vak/issues)

**Describe the bug**

Issue during prepping the evaluation data (own data): the directory contains one wav file and its associated annotation file (in notmat format).

**To Reproduce**
```
Traceback (most recent call last):
  File "/home/vivi/anaconda3/envs/tweetynet/bin/vak", line 8, in <module>
    sys.exit(main())
  File "/home/vivi/anaconda3/envs/tweetynet/lib/python3.8/site-packages/vak/__main__.py", line 45, in main
    cli.cli(command=args.command, config_file=args.configfile)
  File "/home/vivi/anaconda3/envs/tweetynet/lib/python3.8/site-packages/vak/cli/cli.py", line 30, in cli
    COMMAND_FUNCTION_MAP[command](toml_path=config_file)
  File "/home/vivi/anaconda3/envs/tweetynet/lib/python3.8/site-packages/vak/cli/prep.py", line 132, in prep
    vak_df, csv_path = core.prep(
  File "/home/vivi/anaconda3/envs/tweetynet/lib/python3.8/site-packages/vak/core/prep.py", line 205, in prep
    vak_df = dataframe.from_files(
  File "/home/vivi/anaconda3/envs/tweetynet/lib/python3.8/site-packages/vak/io/dataframe.py", line 133, in from_files
    spect_files = audio.to_spect(
  File "/home/vivi/anaconda3/envs/tweetynet/lib/python3.8/site-packages/vak/io/audio.py", line 174, in to_spect
    audio_annot_map = source_annot_map(audio_files, annot_list)
  File "/home/vivi/anaconda3/envs/tweetynet/lib/python3.8/site-packages/vak/annotation.py", line 211, in source_annot_map
    keys = [recursive_stem(annot.audio_path) for annot in annot_list]
TypeError: 'Annotation' object is not iterable
```

Full execution trace (including some print statements inserted by me):

```
(tweetynet) vivi@zfbrain01:~/Projects/Segmentation/TweetyNet/config_files$ vak prep R3406_eval.toml 
determined that purpose of config file is: eval
will add 'csv_path' option to 'EVAL' section
purpose for dataset: eval
will not split dataset
loading annotations from file /home/vivi/Data/Segmentation/voxseg/R3406/Data/035_split_multilabel_vak_test/R3406_40911.54676404_1_3_15_11_16.wav.not.mat
making array files containing spectrograms from audio files in: /home/vivi/Data/Segmentation/voxseg/R3406/Data/035_split_multilabel_vak_test
Annotation files list: Annotation(annot_path=PosixPath('/home/vivi/Data/Segmentation/voxseg/R3406/Data/035_split_multilabel_vak_test/R3406_40911.54676404_1_3_15_11_16.wav.not.mat'), audio_path=PosixPath('/home/vivi/Data/Segmentation/voxseg/R3406/Data/035_split_multilabel_vak_test/R3406_40911.54676404_1_3_15_11_16.wav'), seq=<Sequence with 17 segments>)
Source files list: ['/home/vivi/Data/Segmentation/voxseg/R3406/Data/035_split_multilabel_vak_test/R3406_40911.54676404_1_3_15_11_16.wav']
Traceback (most recent call last):
  File "/home/vivi/anaconda3/envs/tweetynet/bin/vak", line 8, in <module>
    sys.exit(main())
  File "/home/vivi/anaconda3/envs/tweetynet/lib/python3.8/site-packages/vak/__main__.py", line 45, in main
    cli.cli(command=args.command, config_file=args.configfile)
  File "/home/vivi/anaconda3/envs/tweetynet/lib/python3.8/site-packages/vak/cli/cli.py", line 30, in cli
    COMMAND_FUNCTION_MAP[command](toml_path=config_file)
  File "/home/vivi/anaconda3/envs/tweetynet/lib/python3.8/site-packages/vak/cli/prep.py", line 132, in prep
    vak_df, csv_path = core.prep(
  File "/home/vivi/anaconda3/envs/tweetynet/lib/python3.8/site-packages/vak/core/prep.py", line 205, in prep
    vak_df = dataframe.from_files(
  File "/home/vivi/anaconda3/envs/tweetynet/lib/python3.8/site-packages/vak/io/dataframe.py", line 133, in from_files
    spect_files = audio.to_spect(
  File "/home/vivi/anaconda3/envs/tweetynet/lib/python3.8/site-packages/vak/io/audio.py", line 174, in to_spect
    audio_annot_map = source_annot_map(audio_files, annot_list)
  File "/home/vivi/anaconda3/envs/tweetynet/lib/python3.8/site-packages/vak/annotation.py", line 211, in source_annot_map
    keys = [recursive_stem(annot.audio_path) for annot in annot_list]
TypeError: 'Annotation' object is not iterable
```

**Desktop (please complete the following information):**
 - Operating System: Ubuntu 20.04
 - Version [e.g. 22]. You can determine this in Python by running `vak.__version__`: 0.4.1

**Additional context**
Checking if annot_list in annotation.source_annot_map is list and if not putting the element in a list solved the problem.

**Comment by vivinastase** [comment]
Hi Dave

Sorry, I knew the wording would be ambiguous but that's the best I could do :) This is a different issue than 466. That one is about files containing only one annotated segment. This one is about a directory that contains only one file (with its associated annotation file that may contain one or more annotations).

**Comment by NickleDave** [comment]
H again @vivinastase -- just an update that I will add fixing this to the 4.2 release and have a fix by the end of this weekend at the latest. Thank you again for catching it

**Comment by vivinastase** [comment]
Thanks for your help and patience Dave!

**Comment by NickleDave** [comment]
@vivinastase sorry to add to your notifications, but did want to let you know this should be fixed in main, if you don't mind cloning the git repo and installing it locally (I have a feeling you might have things set up that way already)

**Comment by vivinastase** [comment]
Hi Dave
I redid the process from the very beginning (reinstalling tweetynet), and on the same data I used before it all ran smoothly.

**Comment by NickleDave** [comment]
Thank you so much @vivinastase for testing -- glad to hear that it is now running smoothly for you.

I do still have your other suggestions on the to-do list -- like adding an `eval` step to the first tutorial -- but am working on some other dev stuff right now.

We're happy to hear any other feedback you have as you are working with the library!
