### ISSUE TITLE
crowsetta raises unexpected argument error

### ISSUE THREAD

**Issue by muxiaofan** [NickleDave/vak#67]
When calling the vak library, the an error is raised. The Meta class doesn't have an input argument called to_seq. crowsetta version is latest 2.0.0.

Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\User\venv3\Scripts\vak.exe\__main__.py", line 5, in <module>
  File "c:\users\user\venv3\lib\site-packages\vak\__init__.py", line 1, in <module>
    from . import __main__
  File "c:\users\user\venv3\lib\site-packages\vak\__main__.py", line 7, in <module>
    from .cli import cli
  File "c:\users\user\venv3\lib\site-packages\vak\cli\__init__.py", line 3, in <module>
    from .prep import prep
  File "c:\users\user\venv3\lib\site-packages\vak\cli\prep.py", line 5, in <module>
    from .. import dataset
  File "c:\users\user\venv3\lib\site-packages\vak\dataset\__init__.py", line 3, in <module>
    from .classes import MetaSpect, Vocalization, VocalizationDataset
  File "c:\users\user\venv3\lib\site-packages\vak\dataset\classes\__init__.py", line 2, in <module>
    from .vocalization import Vocalization
  File "c:\users\user\venv3\lib\site-packages\vak\dataset\classes\vocalization.py", line 4, in <module>
    from crowsetta import Sequence
  File "c:\users\user\venv3\lib\site-packages\crowsetta\__init__.py", line 13, in <module>
    from .transcriber import Transcriber
  File "c:\users\user\venv3\lib\site-packages\crowsetta\transcriber.py", line 6, in <module>
    from . import formats
  File "c:\users\user\venv3\lib\site-packages\crowsetta\formats.py", line 8, in <module>
    setattr(current_module, entry_point.name, entry_point.load())
  File "c:\users\user\venv3\lib\site-packages\pkg_resources\__init__.py", line 2443, in load
    return self.resolve()
  File "c:\users\user\venv3\lib\site-packages\pkg_resources\__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\users\user\venv3\lib\site-packages\gardner\yarden2seq.py", line 141, in <module>
    to_seq=yarden2seq
TypeError: __init__() got an unexpected keyword argument 'to_seq'

**Comment by NickleDave** [comment]
Hi and thanks for your interest in the library.

Sorry for the confusion: vak still uses crowsetta 1.1.1.
Installing that version should fix this error.

If you're taking the library for a test drive, I would suggest using this data set:
https://figshare.com/articles/Bengalese_Finch_song_repository/4805749
The `yarden` format is specific to one lab and there's not yet any publicly-available datasets with that format.
If you use that repository, the annotation format for the config.ini files would be 'notmat' and the audio format would be 'cbin'. There are some example config files in tests/test_data/configs.

The version of crowsetta vak uses will go up to 2.0.0 in version 0.3.0:
https://github.com/NickleDave/vak/projects/5
but we're trying to get a paper out that's based on the current version, so that won't be until October at least.
